#!/bin/sh


# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

cat /etc/banner
/usr/sbin/vsftpd
mkdir -p /var/log/lighttpd
/usr/sbin/lighttpd -f /etc/lighttpd/lighttpd.conf
/bin/redis-server > /dev/null &
sleep 10
/usr/cms/bin/reboot_wdt.sh > /dev/null &
/usr/cms/bin/cms_mon_proc > /dev/null &
